server:
  port: 8080
  servlet:
    context-path: /CoderSite

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/codersite

# 配置elasticsearch参数
elasticsearch:
  host: 127.0.0.1
  port: 9200
  protocol: http